
### Authorization by token, part 1. Retrieve and save token.
POST https://httpbin.org/post
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.log(response.body.data.token + "...." + client.global.get("auth_token"));
 client.global.set("auth_token", response.body.json.token); %}

###
GET https://httpbin.org/headers
Authorization: Bearer {{auth_token}}